### ISSUE TITLE
Internal Server Error für den Scraper Monitor

### ISSUE THREAD

**Issue by 00Bock** [kjoscha/DataHub#13]
Free floating
Oooops, an error occured: Internal Server Error

**Comment by BenSto** [comment]
>> Free floating
Oooops, an error occured: Internal Server Error

Das liegt z.T. daran, dass immer ein SSH Tunnel/Verbindung zum DataHub aufrecht erhalten bleiben muss, falls dieser aber mal zusammenbricht (aus welchen Gründen auch immer) muss er erst zur Zeit manuell wieder hergestellt werden. Das Problem ist jetzt aber erstmal behoben und auch die stations basierten Daten werden nun performant über den neuen Table station_movements dargestellt, da dieser nun auch die benötigten Indizes hat.
--> closed

ansonsten bitte reopen oder neues Issue anlegen. Danke.
