### ISSUE TITLE
datahub.sublime-workspace

### ISSUE THREAD

**Issue by BenSto** [kjoscha/DataHub#17]
Diese Datei datahub.sublime-workspace sollte auf keinen Fall in das Repository geladen werden! @kjoscha  Dort ist die komplette File History der Sublime Projekte zu sehen...

**Comment by 00Bock** [comment]
hey.. die Datei ist ja noch drin? sollten wir das nicht löschen?

**Comment by kjoscha** [comment]
yes

**Comment by kjoscha** [comment]
aber aus der History bekommen wir die glaub ich eh nicht
